### PR TITLE
Add Joanna Sese as greeter

### PR DESCRIPTION
**Pull request by joannasese**

### CODE REVIEW

**Comment by joannasese** [comment]
@bhuga @bhelx whoever i'm supposed to poke, i'm poking

**Comment by bhelx** [comment]
I'll test it. bhuga can merge.

**Comment by bhelx** [comment]
Screen Shot 2019-05-29 at 5 49 48 PM

@bhuga looks good to merge.
Thanks @joannasese

**Comment by bhelx** [comment]
Nevermind, seems I've been given the power ⚡️

**Comment by bhuga** [comment]
> Nevermind, seems I've been given the power ⚡️

giphy (1)

**Pull request merged**
