### PR TITLE
Invasion of the SpaceOtters

### PR DESCRIPTION
**Pull request by SpaceOtterInSpace**
now it looks great

### CODE REVIEW

**Comment by SpaceOtterInSpace** [comment]
sscl

**Comment by joeellis** [comment]
non-blocking design critique:  needs more hat.

but, :+1: for :ship:

**Comment by bhuga** [comment]
we should make this a 2x2 grid:

```
[X] [X]
[X] [X]
```

**Comment by joeellis** [comment]
i miss our gonfalon flag

**Comment by SpaceOtterInSpace** [comment]
I fixed the 2x2 thing

**Comment by bhuga** [comment]
Screenshot monster demands more!

protop: you can do a non-gif, perhaps easier than licecap, with cloudapp.

**Comment by SpaceOtterInSpace** [comment]
sscl2

**Comment by joeellis** [comment]
can you add my hat?

joe-pretty-hat

**Comment by SpaceOtterInSpace** [comment]
I see how it is... I'm so awesome everyone just needs to copy me and my hat.

**Comment by joeellis** [comment]
well your hat is :cool: , so now i worry i'm gonna look all dumb without a hat

**Comment by joeellis** [comment]
i'm pretty ++ to anything that makes people look at the hats more

**Comment by SpaceOtterInSpace** [comment]
accept me!!!

**Pull request merged**
